#!/bin/bash
echo "Started to prepare python scripts"
cat << EOF > pyflowline.py
from pyflowline.pyflowline_read_model_configuration_file import pyflowline_read_model_configuration_file
sFilename_pyflowline_configuration = "/qfs/people/liao313/workspace/python/pyhexwatershed/tests/configurations/template.json"
oPyflowline  = pyflowline_read_model_configuration_file(sFilename_pyflowline_configuration)
oPyflowline.setup()
oPyflowline.run()
oPyflowline.analyze()
oPyflowline.export()
EOF
