#!/bin/bash
#SBATCH -A ESMD
#SBATCH --job-name=hexpyhexwatershed20220308001
#SBATCH -t 1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=short
#SBATCH -o stdout.out
#SBATCH -e stderr.err
#SBATCH --mail-user=chang.liao@pnnl.gov
cd $SLURM_SUBMIT_DIR
module purge
module load gcc/8.1.0
module load anaconda3/2019.03
source /share/apps/anaconda3/2019.03/etc/profile.d/conda.sh
./hexwatershed .ini
