from pyhexwatershed.operation.postprocess.plot.pyhexwatershed_plot_elevation import pyhexwatershed_plot_elevation
from pyhexwatershed.classes.pyhexwatershed_read_model_configuration_file import pyhexwatershed_read_model_configuration_file
sFilename_configuration_in = '/qfs/people/liao313/workspace/python/pyhexwatershed/pyhexwatershed/config/hexwatershed_susquehanna_mpas.json'
oModel = pyhexwatershed_read_model_configuration_file(sFilename_configuration_in)

pyhexwatershed_plot_elevation(oModel)

print("Finished")